#!/bin/bash
echo " enter  your name "
read name
echo " your name $name "
echo "friend name $0 $1 "
                                                                                                                  ~                            
